Bear-Algorithm-Team/bearalgorithm

solutions/minwoo/SWExpertAcademy/1244_최대상금.py
Link
====
Approach
====  
문제 설명그대로 직관적으로 풀이를 함. 
각 라운드 마다 자리를 바꾸는 모든 경우의수를 만들어내고, 이를 set으로 관리함 (가지치기를 알아서 해줄 수 있도록) 
====  
N(숫자의 길이) : 6
K(교체횟수/라운드) : 10 
O(K*(N^2)^2 ) 
====  
====  
시간복잡도:
N^2 을 순회하면서  N^2개 만큼의 경우의 수를 만들어낼것임 (여기서 중복을 제거하면 더 작아짐)
N^2개 만큼의 경우의 수(set_temp)가 다음라운드에 쓰이게 되고, 각 경우의 수마다 또 N^2 을 순회함
=> [PS-67] 1244 최대상금

pull_request_template/bear_template.md
Changelog
====
- Pull request template 폴더 삭제 (베이스 템플릿외에 굳이 다른 템플릿을 둘 필요성이 없어짐. 또한, PR 을 올릴때 직접 링크를 템플릿 이름과 맞춰줘야해서 오히려 불편함.)
====
=> [PS-71] template refactoring

solutions/minwoo/baekjoon/아기상어.py
Link
====
https://www.acmicpc.net/problem/16236
백준 삼성 기출문제집 수록
Approach
====  
시뮬레이션 + BFS
====  
O(NM* BFS수행 횟수) BFS 수행 횟수는 물고기의 수 만큼이므로 최대 NM-1 번 
최종으로 O((NM)^2) 
====  
====
=> [PS-73 아기상어]

solutions/minwoo/baekjoon/2206 벽부수고 이동하기.py
Link
====
https://www.acmicpc.net/problem/2206
Approach
====  
BFS 기본유형이나, 벽을 부술수 있는 조건이 추가되어 한 차원이 더 필요하다.
이를 '층'으로 접근해서, 벽을 부수면 '1층계' 에서 BFS를 돌리고 , 그 외는 '0층계' 에서 BFS를 돌린다.
====  
O(NM)
====  
====  
기본 BFS,DFS 유형인데, 조건추가로 문제를 조금 헷갈리게 하는 유형들이 종종 보임
=> [PS-72] 백준2206 벽부수고 이동하기

solutions/kangwook/코드트리/코드트리 빵.py
Link
====
https://www.codetree.ai/training-field/frequent-problems/problems/codetree-mon-bread/
Approach
====  
각 사람마다 각자만의 BFS 순회를 위한 큐를 할당하고, 매 분마다 각 사람마다 BFS를 **depth를 하나씩만 늘려나가는 식**으로 수행한다.
====  
O(m n^2)
====  
====  
- 이 문제에서 응시자들에게 요구하는 것은 첫째로 그냥 단순히 매 분마다 bfs depth를 하나씩만 늘려가는 식으로 bfs 순회를 하면 문제가 간단히 풀리는 것을 포착하는 거. 문제에서 일어나는 상황을 충분히 이해했으면 매 분마다 사람이 움직인다는 사실을 상상할 수 있고, 이 움직임이 가능한 경로를 모두 BFS를 수행하는 큐에 담고 매 분마다 차근차근 BFS depth를 늘려가는 식으로 순회하는 것을 문제의 각 조건이 모두 허용하고 있다는 사실을 문제를 꼼꼼히 읽으면 확인할 수 있다.
- 이 문제가 개인적으로 굉장히 더럽다고 생각하는 부분은, (1)움직이고 있던 사람들이 움직인다 (2)그 다음에 다음 사람이 베이스캠프로 배치된다 이 순서를 정확히 코드 안에서 구현해야 한다는 점. 이 문제가 어떻게 풀리는지 알고리즘을 파악했다 해서 이 문제의 정답을 찾은 게 되는 게 아니고, 이 문제는 '이 순서가 달라지면 오답을 출력하는 테스트케이스가 있을 수 있다'라는 걸 문제를 읽고 포착을 하고 이를 구현에 …
=> [PS-87] 코드트리 빵

solutions/kangwook/programmers 연습문제/인사고과.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/152995
Approach
====  
1. s[0] 기준으로 내림차순, s[1] 기준으로 오름차순 정렬 한다.
2. s[1]이 오름차순으로 증가하는 수열을 filtering해서, 이들만을 대상으로 정답을 계산한다.
====  
O(n)
====  
====  
- 깊게 생각하지 않아도 일단 s[0]를 기준으로 내림차순 정렬을 한다음에 앞에서부터 하나씩 체크하면 답을 구할 수 있다는 걸 어렵지 않게 알 수 있는 문제.
- 다만 s[1]를 어떻게 할지 분명한 원칙이 안 떠오를 수 있고, 이러면 's[0]이 같은 경우에는 s[1]도 내림차순'이라는 원칙을 일단 정하고 그 다음에 알고리즘을 구현할 수도 있다. 그러나 이 문제는 그렇게 구현할 경우 구현이 다소 복잡해진다. if문을 여럿 쓰고 캐싱도 대기열 사용해서 복잡하게 해야 한다.
- 여기서, 애초에 's[1]에 대해서는 오름차순'이라는 원칙을 세우고 문제를 접근하면 문제를 푸는 로직이 훨씬 간단해짐을 알 수 있다.
=> [PS-84] 프로그래머스 Lv.3 인사고과

solutions/kangwook/백준/17143_낚시왕.py
Link
====
https://www.acmicpc.net/problem/17143
Approach
====  
이 문제는 1초 뒤 상어 위치를 어떻게 구하느냐가 중요. 상어의 초당 이동 칸수가 전체 격자판의 너비보다 클 수 있으며, 상어는 벽에 부딪히면 방향을 반대로 바꿔 이동한다. 이 특징을 이용해, 나머지 등 수식계산을 통해 1초 뒤 상어 위치를 빠른 시간 안에 구할 수 있다.
====  
O(n^4)
====  
====  
- 수식계산을 통해 상어의 위치를 빠른 시간 내에 구할 수 있다는 아이디어를 갖고 문제에 접근했는데, 디버깅에 너무 많은 시간을 써서 결과적으로 그냥 루프를 돌려 1씩 이동시켜 구현했으면 금방 구현했을 것 같은데 생각보다 훨씬 오랜 시간이 걸렸다. 복잡한 수식 계산을 통해 빠르게 답을 구하는 게 더 좋을 때도 물론 있겠지만, 실제 문제를 풀 땐 구현 방식에 따라 디버깅에 오랜 시간이 걸릴 수 있다는 점, 그리고 정확한 시간복잡도를 고려해 최대한 빨리 구현할 수 있는 구현 방식으로 구현하는 게 좋겠다.
- 다만 실제 연습 과정에서는 이런 형태의 수식 계산을 연습해두는 것이 반드시 언젠가 써먹을 때가 있으므로 나쁘지 않은 연습 시간이었다고 생각된다.
=> [PS-92] 백준 17143 낚시왕

solutions/minwoo/leetcode/152.Maximum subarray product.py
Link
====
https://leetcode.com/problems/maximum-product-subarray
Approach
====  
다이나믹 프로그래밍을 사용해서 풀 수 있다.
주의할점은, 양수, 음수의 곱셈이 모두 가능하기 때문에 최솟값이 최댓값으로 역전될 수도 있다는 점이다.
따라서, 해당 인덱스까지의 최솟값,최댓값을 둘 다 관리하는 방식으로 문제를 해결할 수 있다.
그리고 dp배열을 쓸필요도 없다.
====  
O(N)
====  
O(1)
====  
온사이트 코딩테스트에서 충분히 나올법한 문제인듯
=> [PS-97]Maximum subarray product

solutions/minwoo/leetcode/5. Longest palindromic substring.py
Link
====
https://leetcode.com/problems/longest-palindromic-substring/description/
Approach
====  
사고의흐름1) subsequence 가 아니라, substring 문제이므로 완전 탐색을 진행해야한다.
2) N^2으로, substring 을 만들고, 팰린드롬을 확인하려면 N^3 이된다 -> 시간초과
3) substring을 만드는 과정과 팰린드롬 체크 과정을 하나로 합쳐야 한다. -> 팰린드롬의 특성상, 가운데기준으로 양쪽의 문자가 같아야한다.
4) N으로 순회하면서 해당 Index 기준으로 투포인터를 써서 양쪽을 벌려가며, 팰린드롬 체크를 바로 하면, O(N^2)으로 해결가능하다.
====  
O(N^2)
====  
====
=> [PS-88] longest palindromic substring

solutions/minwoo/programmers/단속카메라.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/42884
Approach
====  
가로 막대 그래프로 도식화하면 쉽게 보임. 
먼저 나가는 차량 순서대로 정렬을 하고, 
현재 차량이 나갈때, 감속카메라의 위치를 보면된다. 
1) 만약 감속카메라의 위치가, 현재차량이 들어오기 전 위치에 있다면 , 해당차량을 감시하지 못했으므로, 차량이 나가는 거리에 설치한다.(최대한 멀리설치 해야 이득)
2) 그외의 경우에는, 차량을 감시한 경우이므로 pass 한다.
====  
O(N)
====  
====  
막대그래프로 도식화해서 푸는 그리디 유형의 문제들이 자주보인다
=> [PS-91]단속카메라

solutions/minwoo/baekjoon/17143 낚시왕.py
Link
====
https://www.acmicpc.net/problem/17143
삼성기출 시뮬레이션 문제
Approach
====  
시뮬레이션 유형. 
상어의 상태를 좌표에 Array로 넣어서 관리하며, 순회하면서 시뮬레이션을 하는 방식으로 접근하였다.
====  
O(N*M^2)
====  
====  
상어를 이동한다음, 맵 업데이트를 할때에 실수가 있었다. 
상어를 한마리 이동할때마다, 기존 위치는 지우고, 새로운 위치로 옮기는 작업을 한개의 맵에 순차적으로 적용했는데,
문제조건에서 상어는 동시에 이동하므로.. 이렇게되면 순서가 완전 꼬이게된다. 
깔끔하게 새로운 맵에 업데이트 하고 덮어씌우는 방식으로 했었어야했다. 
시뮬레이션 문제는 특히문제를 잘 읽어야겠다. 하지만 break 포인트지점만 잘 잡아도 디버깅속도를 빠르게 할 수 있어서, 기능별로 함수로 나눠서 구현한게 도움이 많이 됐다.
=> [PS-81] 백준 낚시왕

solutions/minwoo/leetcode/424. Longest Repeating Character Replacement.py
Link
====
https://leetcode.com/problems/longest-repeating-character-replacement
Approach
====  
슬라이딩 윈도우 , 해시 맵
반복되는 가장 긴 문자열을 찾되, k개 만큼 원하는 알파벳으로 바꿀 수 있다.
인덱스를 증가시켜가면서 window를 잡는 개념을 떠올릴 수 있다. 서로다른 알파벳이 k개 초과 일때, window사이즈를 줄이면 되기때문이다. 
그리고 이를 구현하기위해서는, 테이블이 하나 필요한데, 윈도우 구간안에 해당 알파벳이 몇번 등장하는지를 트래킹 해주어야한다. 
====  
O(N)
====  
O(1)
====
=> [PS-103] 424. Longest Repeating Character Replacement

solutions/minwoo/programmers/디스크 컨트롤러.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/42627
Approach
====  
최소힙을 2개 사용한다. 
q1: 대기큐 ( 먼저 들어온 순대로 관리)
q2: 실행큐 (가장 짧은 실행시간 순서대로 관리)
아이디어 : 시뮬레이션 하듯이, 현재 시간에 진행할 수 있는 프로그램을 대기큐 -> 실행큐로 옮긴다. 
====  
O(nlogn)
====  
====  
이 문제는 완벽하진 않은것 같다.(반례존재)
또한 지문에 함정이 있는데, "디스크는 아무것도 하지않으면 먼저 들어온 작업을 처리한다" 이다.
따라서, 단순히 "먼저끝나는 순으로 정렬하고, 같으면 먼저 시작하는 순으로 정렬한다" 가 통하지 않는다.
만약 위 조건이 없었으면, 실행시간을 가장 최적화 하는방법은, 먼저 끝나는 프로그램 순으로 처리하는게 그리디 접근법에서 맞다.
처음엔 단순히 위처럼 풀어서 정답을 받을 수 없었음.
```python
from collections import deque
def solution(jobs):
n = len(jobs)
for i in range(len(jobs)):
jobs[i] = [jobs[i][0], jobs[i][0] + jobs[i][1]] # 시작시간,끝나는시간으로 바꿔서 해석함 편하게..
jobs.sort(key=lambda x: (x[1], x[0]))
jobs = deque(jobs)
cur_s, cur_e …
```
=> [PS-86] 디스크 컨트롤러

solutions/kangwook/programmers 연습문제/코딩기초트레이닝 가장긴부분문자열.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/181872
Approach
====  
파이썬 index 메서드의 사용
====  
O(n)
====  
====  
- 쉬운 문제를 빨리 많이 푸는 느낌을 되살려보려고 프로그래머스 코딩기초트레이닝을 풀어보는데 파이썬 문법사항 몇가지 안 익숙한 걸 발견해서 PR 만들어보았다. PS를 위해 너무 많은 메서드를 세세히 외워둘 필요는 없고 직접 구현해도 시간복잡도상으로 이득에 차이가 나지 않는 경우도 많지만 index 같은 너무 기초적인 메서드는 확실히 외워두는 게 훨씬 낫고 여태 몰랐다는 게 좀 부끄러운 일이니 이번 기회에 확실히 기억해야겠다.
- 이 문제는 rindex를 이용하면 조금 더 빨리 풀 수 있지만, 여기 코드와 마찬가지로 index를 쓰더라도 구현 시간에 별 차이는 없는것같다.
- 파이썬의 index 메서드와 find 메서드는 서로 거의 동일한 기능을 하지만 다음 차이가 있다.
- find: 문자열에 대해서만 사용 가능. 찾는 문자열이 없다면 -1 리턴.
- index: 리스트에서도 사용 가능. 찾는 엘리먼트 없다면 value error 리턴.
=> [PS-102] 프로그래머스 코딩기초트레이닝 가장긴부분문자열

solutions/kangwook/programmers 연습문제/억억단을 외우자.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/138475
Approach
====  
1. 1부터 e까지 각 수의 약수의 개수를 센다.
2. 약수의 개수를 저장한 배열을 거꾸로 세면서 각 지점까지 약수 개수가 최대인 수를 기록한다.
3. 2번에서 얻은 값을 활용해 답을 리턴한다.
====  
O(n log log n). 약수 개수 구하는 부분이 가장 시간복잡도가 오래 걸리고 나머지는 O(n)인데, 약수 개수 구하는 부분의 루프 반복횟수는 에라토스테네스 체의 루프 반복횟수와 같고 이 시간복잡도가 O(n log log n)임이 잘 알려져 있다.
====  
====  
- 약수의 개수를 세는 코드 구현이나, 각 범위 안에서 약수 개수가 최대인 수를 구하는 코드 구현이나 굉장히 간단하게 할 수 있는 코드가 있는데, 문제의 조건을 꼼꼼히 읽고 깊게 생각하지 않으면 떠올리기 쉽지 않다. 개인적으로는 처음에 약수 개수 구하는 코드를 memoization으로 구현했고 범위별 약수 개수가 최대인 수를 구하는 코드를 세그먼트 트리로 구현하려고 했는데, 알고리즘 자체도 시간초과였고(분명히 시간복잡도는 정답코드랑 같은데) 세그먼트 트리는 범위를 구하기 위한 순회를 구현하다 디버깅에 너무 오래 걸려서 100줄 넘게 쓰고도 결국 완성하지 못했다. 얼핏 다른 사람들 코드를 봤는데 10줄 남짓 안 되는 코드로 푼 것을 보고 놀라서 읽어보고 …
=> [PS-98] 프로그래머스 연습문제 억억단을 외우자

solutions/kangwook/programmers 연습문제/그리디 조이스틱.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/42860
Approach
====  
그리디..로 풀어야 하는데 생각하기 귀찮아서 BFS로 품;;
====  
O(2^n)
====  
====  
예전에 C++로 PS 하던 시절에 그리디하게 풀려고 머리 많이 굴려보았으나 디버깅이 잘 안 돼서 덮었던 문제. 또 디버깅하기 귀찮고 뭐 하나 빨리 풀어보고 싶어서 이번에는 그냥 BFS 빨리 구현하면 얼마나 빨리 구현할 수 있나 연습겸 BFS로 구현해보았다. 하지만 그리디로 잘 풀기 위해 필요한 생각을 연습할 필요를 느낀다면 이 문제를 그리디로 다시 풀어보는 게 필요할 것 같다.
=> [PS-101] 프로그래머스 그리디 조이스틱

solutions/minwoo/baekjoon/2493. 탑.py
Link
====
https://www.acmicpc.net/problem/2493
Approach
====  
스택. 왼쪽 -> 오른쪽으로 진행하면서, 누적된 왼쪽을 살펴야 하는문제이므로, 정방향 순회를 하되, 스택을 이용하면 풀 수 있다는 아이디어를 떠올릴 수 있음.
====  
O(N)
====  
O(N)
====
=> [PS-112] 탑

solutions/kangwook/programmers 연습문제/과제진행하기.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/176962
Approach
====  
스택
====  
O(n)
====  
====  
- 굉장히 쉬운 평범한 스택 문제인데, 알고리즘 측면에서 흥미로운 점이 있는 게 아니라 오랜만에 파이썬 zip 함수 / unpack 연산자를 연습할 수 있는 코드를 써볼 기회를 얻어서 한번 풀고 관련 내용을 정리해보았다. zip, unpack 연산자는 잘 쓰면 굉장히 강력한데 많이 연습해보지 않아서 개인적으로 낯설게 느낀 구문이라 이번 기회에 연습할 수 있어서 좋았다. 아래는 챗지피티에 물어본 zip(*arr)의 의미.
> 만약 arr가 리스트의 리스트라고 가정하면, zip(*arr)는 arr 내부의 각 리스트들을 언팩한 후 zip으로 다시 묶어주는 작업을 수행합니다. 이는 행렬의 전치(transpose) 연산과 유사하게 동작합니다.
=> [PS-109] 프로그래머스 과제 진행하기

solutions/kangwook/kakao/2023 표현 가능한 이진트리.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/150367#
Approach
====  
분할정복. 사실 depth가 깊어질수록 같은 패턴이 반복될 수 있어 캐싱을 해두면 좀 더 시간상 이득을 볼 수 있긴 한데, 구현해보니 그런 부분을 구현하지 않아도 충분히 빠른 시간 안에 패스가 가능했다.
====  
- O(n log n). 재귀호출을 깊게 하다 보면 결국 길이가 1인 문자열까지 내려가는데, 재귀호출의 깊이가 최대 log n이므로 전체 시간복잡도는 매우 짧다. 
- 주어진 문자열의 정 가운데 문자가 "0"인 경우 O(n)의 시간복잡도를 갖는 체크 코드가 추가되긴 하는데, 이 경우 거기서 더 재귀호출을 진행하지도 않고 **분할정복 특성상 이미 한 검사를 다시 반복하는 경우가 없기 때문에** 결과적으로 이 체크 코드로 인한 반복횟수가 **다 합해 n보다 커지지가 않는다.**
====  
====  
- 사실 캐싱 부분 까지 추가된 전체 코드 구현을 굉장히 빨리 했는데, 2진수로 변환한 문자열 앞에 "0"을 충분히 채울 때 채우는 개수를 세는 코드에 오류가 있어서 디버그하는데 굉장히 많은 시간이 들었다.
- PS를 하면서 디버그 시간을 줄이기 위해 가장 필요한 실력은, 사실, **한줄 한줄 코드를 꼼꼼히 읽으면서 모든 연산자와 숫자의 의미를 토씨 하나까지 완벽히 이해하는 집중력**이다. '**여기서 왜 더하기/빼기 1을 …
=> [PS-100] Kakao 2023 표현 가능한 이진트리

solutions/minwoo/kakao/2022.등산코스 정하기.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/118669
Approach
====  
BFS + 가지치기 유형
1. 올라갈때 내려갈때 동일한 경로로 등반하면 되기때문에 올라가는 경우만 생각하면된다.
2. BFS로 최소 intensity를 유지하면서 봉우리까지 가는 경로를 탐색한다.
3. BFS는 depth가 동일한 순서대로 알고리즘이 진행되기때문에, 같은 노드라도, intensity가 더 낮은 여러 노드들을 거쳐서 재방문 될 수 있다. 따라서 가지치기를 진행할 수 있다. 
탐색+가지치기 문제유형 많이 풀어봐야겠다. 
가끔 가지치기가 전혀안되고있는데.. 가지치기를 하고있다고 착각하는경우가 있음
====  
O(E) E: 간선 
노드는 결국 중복방문될수있고, intensity로 가지치기를 하기때문에, 
결국 모든 간선을 순회하는 시간복잡도를 갖게됨.
====  
====
=> [PS-105] 등산코스 정하기

solutions/kangwook/programmers 연습문제/디펜스게임.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/142085#
Approach
====  
힙
====  
O(n lg n)
====  
====  
- 리스트의 원소를 처음부터 하나씩 읽으면서 힙에 넣고, 매 루프마다 하나씩 힙에 넣고 빼면서 힙에서 뺀 걸 n에서 하나씩 빼가면서 최대한 반복할 수 있는 루프 횟수를 리턴하는 문제.
- 힙으로 풀면 굉장히 간단하게 풀 수 있는 힙 자료구조 연습용 문제라고 할 수 있는데, 문제가 되게 dp 문제 비슷하게 생겨서 '힙'이라는 아이디어가 안 떠오르면 'dp인가? 입력 조건이 저렇게 큰데?' 하고 한참 헤맬 수 있다. 하필 memoization 문제를 본 직후에 봐서 memoization인 줄 알고 memoization으로 구현했다가 시간초과를 보고 한참 고민.. 
- 이렇게 아이디어를 떠올리면 금방 풀 수 있는 문제가 2시간 이하 짧은 코테에 자주 출제되는 거 같다. 문제를 빨리 풀기 위해서는 '이 방법인가?' 하고 확신이 들더라도 좀 더 차분하게 문제를 전체적 시각에서 보며 조건 하나하나 뜯어볼 필요가 있는 것 같다. 특히 자료구조 선택을 잘하면 쉽게 풀리는 문제들 중에 이런 문제가 많았던 것 같다.
=> [PS-115] 프로그래머스 디펜스게임

solutions/kangwook/programmers 연습문제/광물캐기.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/172927
Approach
====  
memoization. dp[(dia, iron, stone)] = 곡괭이를 (dia, iron, stone)개 사용했을 때 최소 피로도
====  
O(n^3) (0 <= n <= 5)
====  
====  
- 간단한 memoization 문제. 문제의 조건을 잘 뜯어보면 minerals 배열을 5개 단위로 끊어서 생각하면 되는 걸 알수 있다. 얼핏 생각하면 재귀호출 쓰지 않고 순차적으로 하나씩 읽어도 되지 않나 싶을 수 있는데 그렇게 했을 땐 구현이 굉장히 복잡해지는 측면이 있다. 그러나 memoization으로 구현하면 꽤 간단하게 풀린다.
- memoization이라는 걸 알면 레벨2라는 난이도가 납득이 가는데 바로 떠오르지 않는다면 푸는 데 좀 시간이 걸리는 문제 같다. 이게 내가 memoization에 안 익숙해서 그렇게 느끼는 것 같긴 한데.. 이런 문제를 더 많이 풀어서 어서 memoization에 많이 익숙해져야겠다.
=> [PS-114] 프로그래머스 광물캐기

solutions/minwoo/kakao/2018_프렌즈4블록.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/17679
Approach
====  
시뮬레이션 , BFS
이문제의 포인트
1. 2x2 블럭을 한번에 터뜨려야함. 
2. 터뜨린 후 블록을 내려주어야함 
2번을 BFS로 깔끔하게 구현했음. 
강욱님 덕분에 이런 문제들을 풀다보니 BFS 혹은 DFS 로 바로 접근할 수 있는 방법이 빨리 떠올랐고, 짤 때 가독성있게 짜려고 노력하는중..
====  
O( n*m*수행횟수(n*m) )
====  
====
=> [PS-117] 프렌즈 4블록

solutions/minwoo/programmers/메모장.py, solutions/minwoo/programmers/숫자뽑기.py
Link
====
숫자뽑기: https://school.programmers.co.kr/learn/courses/11133/lessons/71166
메모장 : https://school.programmers.co.kr/learn/courses/11133/lessons/71167
Approach
====  
숫자뽑기 : 그리디, 슬라이딩 윈도우
1. 먼저 오름차순 정렬을 한다. 
2. K개를 뽑아서 만든 부분배열의 요소의 최대, 최소의 차이가 가장 작으려면,  연속된 K개를 뽑은다음, 최대 - 최솟값이 가장 최적의 해(정렬이 되어있으므로)이다. 따라서 연속된 K개의 슬라이딩 구간중 맨 앞,맨끝을 보면서 정답을 도출한다.
메모장: 시뮬레이션 
1. 단어와 단어사이에는 공백이 존재해야하고, 단어가 문장의 맨 끝에 있을때는 공백이 없어도됨. 따라서 일단 단어를 붙여서 임시문장을 만든다음, 길이가 K 이하인지, 초과인지에 따라 처리하면 간단히 풀림
====  
숫자뽑기 : O(N)
메모장: O(N)
====  
====
=> [PS-120] 숫자뽑기, 메모장

solutions/minwoo/programmers/여행경로.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/43164
Approach
====  
DFS 백트래킹 
평소에 DFS를 풀때, 글로벌 변수들을 많이 활용했는데 강욱님 코드들, 재귀 잘짜는 사람들 보니까 재귀함수의 리턴값을 결과로 받아서 처리하는 코드들이 훨씬 좋아보였음.
그동안 글로벌 변수를 활용한 이유는 기저조건을 잘 설정하고, 원하는 깊이에 도달했을 때 답을 저장 해주기만하면 코드 짜기가 매우 쉬워지기때문.
그러나 글로벌변수 활용은 실수/디버깅 시 좋지않음. 또한 답을 출력할때 불필요한 코드들이 들어간다.
재귀문제푸는 습관을 고치는게 좋을것같다
====  
O(N)
====  
O(N) : 재귀깊이
====
=> [PS-118] 여행경로

solutions/kangwook/programmers 연습문제/숫자카드나누기.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/135807
Approach
====  
한쪽 배열의 최대공약수만 구해서 이걸로 계산하면 되는 문제
====  
O(n)
====  
====  
1. `math.gcd`의 사용법 정도는 기억해두는 게 좋은 것 같다. 주의할 게, python 3.5 이후 버전부터는 math.gcd 함수는 3개 이상의 인자도 받지만, 그 이전의 버전은 오직 두 개의 인자만 받고, 프로그래머스의 파이썬은 3.5 이전 버전이다.(;;)
2. 다른 사람의 정답 풀이를 보았을 때 `functools.reduce`를 사용하는 코드들이 제법 있는데, 좋은 활용이라고 생각하긴 하지만 개인적으로 찾아보았을 때 조금 번거로운 부분이 많은 함수라 생각되어 굳이 내 코드를 수정하지는 않았다. (functools.reduce의 첫 인자는 '인자를 두 개 받는 함수'여야 하고 둘째 인자는 리스트가 돼야 하는데, 리스트의 첫 두 인자가 먼저 함수의 인자로 전달되고 그 다음부터 앞 루프의 결과값이 다음 루프에서 인자로 전달되는.. 좀 복잡한 메커니즘으로 작동하는데 실제 코테 환경에서 갑자기 쓰려 할 경우 헷갈려서 시간만 더 쓸 거 같다.)
=> [PS-113] 프로그래머스 숫자카드나누기

solutions/kangwook/kakao/2020 기둥과 보 설치.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/60061
Approach
====  
시뮬레이션
====  
O(n)
====  
====  
- 복잡한 알고리즘은 딱히 없고, 기둥과 보를 설치할 때 충분히 그 위치가 안전히 설치될 수 있는지, 삭제할 때 삭제하더라도 주변에 그 기둥/보를 지지하는 다른 기둥/보가 안전히 존재할 수 있는지 복잡한 조건식을 따져가면서 구현하면 되는 문제. (그래도 아무리 실수 안하려고 해도 +1, -1 헷갈릴 때가 있는 건 어쩔 수 없는 듯. 이런 문제는 이거 안 틀리는 게 너무 중요한데, 안 쓰고 하면 실수할 수밖에 없는 것 같다. 쉽고 단순해 보이는 문제라 해도 꼼꼼히 생각하고, 틀리지 않도록 꼼꼼히 숫자를 쓰면서 문제를 풀자.)
- 기둥/보를 설치할 때 그 위치가 안전한 위치인지를 판단하는 조건식은 매우 단순해서 구현이 어렵지 않으나, 삭제할 때 삭제해도 되는지 조건식을 쓰는 게 굉장히 복잡하고 까다롭고 헷갈리기 너무 쉬운 문제. 처음에는 따로 함수를 쓰지 않고 그냥 한 줄에 조건식을 쓸 수 있을 줄 알고 그렇게 했는데, 너무 길어지고 복잡하고 빼먹는 조건이 너무 많아서 그제야 새로 함수를 쓰는 게 낫다는 걸 깨닫고 함수부터 구현. reliable한 함수를 구현 후 bottom up으로 전체 코드를 쓰는 게 OOP의 기본 이념인데 왜 이게 좋은 아이디어인지를 이런 복잡한 시뮬레이션 …
=> [PS-123] 2020 카카오 블라인드 기둥과 보 설치

solutions/minwoo/programmers/상담원인원.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/214288
Approach
====  
1. 상담유형 별로 상담사를 어떻게 배치할 수 있을지 중복조합으로 완전탐색한다.
2. 우선순위큐를 사용한다 
Interval, 스케줄 관련 문제들 많이 풀어봤는데, 이 문제는 각 상담사유형별로 큐를 관리하는 조건이 추가되었다.
물론 상담사 유형별로 힙큐를 나누지않고, 큐를 전체순회하면서 맞는 type이 나올때 까지 뽑아도 됨 -> 비효율
1번만 잘 나눴으면 평이한 스케줄문제
====  
5H20 가지. (중복조합)
====  
====
=> [PS-122]상담원 인원

solutions/minwoo/baekjoon/1689 겹치는선분.py
Link
====
https://www.acmicpc.net/problem/1689
Approach
====  
interval 문제. 
겹치는 구간의 갯수만 중요하므로 시작지점과 끝지점을 분리해서 배열에 넣어주고 시간순으로 정렬해주면, 겹치는 구간을 셀수있다.
겹치는구간 갯수카운트하는 응용문제들도 대부분 간단하게 시작,끝 분리 방식으로 풀 수 있는데 대표적인 유형이라 풀어봤다!
====  
O(N)
====  
====
=> [ps-131] 1689 겹치는 선분

solutions/minwoo/codetree/놀이기구탑승.py
Link
====
https://www.codetree.ai/training-field/frequent-problems/problems/go-on-the-rides/description?page=1&pageSize=20
Approach
====  
삼성 2021 상반기 1번 기출문제복원 
각 학생을 hash에 저장하고, 친한친구들은 set 자료형으로 hash의 value에 저장한다.
그 이후에는 단순히 시키는대로 구현하면 꼬일부분이 없었던 문제
삼성문제는 시뮬레이션 흐름대로 푸는게 편해서, 지문에 등장하는 순서대로 step1... 식으로 네이밍 하고, 그 안에서 필요한 함수들은 따로 네이밍 하는 것이 디버깅하기도 쉽고 가독성이 좋은것같아서 여러가지 스타일을 시도중 입니다.
====  
====  
====
=> [ps-132] 놀이기구 탑승

solutions/kangwook/programmers 연습문제/최적의행렬곱셈.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/12942
Approach
====  
DP
====  
O(n^3)
====  
====  
- 간단한 2차원 DP 문제. 너무 DP를 안풀어봐서 까먹을까봐 감 살리는 차원에서 풀어봤다.
=> [PS-124] 프로그래머스 최적의 행렬 곱셈

solutions/kangwook/kakao/2023 표 병합.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/150366#
Approach
====  
Union Find
====  
O(k * n^3) (n = 50, k = 커맨드 수. 사실상 O(n)) 단, 유니언 파인드에서 부모 찾으면서 부모 갱신하기를 하는 코드를 추가하면 거의 O(k * n^2)으로 줄어듦. (이 문제에서는 굳이 그럴 필요는 없긴 함.)
====  
====  
- 간단한 유니언 파인드 문제. 대충 merge 이후 셀 사이 관계가 리스트 내지는 트리 구조여야 한다는 감은 금방 떠올릴 수 있는데 유니언 파인드가 익숙하지 않으면 구현 난이도가 높다고 생각해서 구현에 시간이 조금 걸릴 수 있는 문제 같다. 
- 개인적으로는 디버깅하는데 너무 오래 시간이 걸렸다. merge 부분을 구현할 때 조건이 굉장히 복잡한데 꼼꼼히 안 읽고 구현한 부분도 있고, merge 부분에서 문제에서 알려주지 않은 까다로운 처리(이미 머지된 셀들 머지하는 커맨드 입력)를 필요로 해서 이 부분 파악하는 데도 굉장히 시간이 오래 걸렸다. (1)**문제를 꼼꼼히 읽는 건** 언제나 가장 중요하다. (2)문제는 happy case만 알려주는 경우가 많아 마치 그런 것만 들어올 거라고 착각할 수 있지만 **채점은 언제나 꼼꼼히 생각해야 떠올릴 수 있는 edge case들이 들어온다**는 걸 항상 명심해야 한다.
=> [PS-121] 2023 카카오 블라인드 표 병합

solutions/kangwook/백준/19263_청소년상어.py
Link
====
https://www.acmicpc.net/problem/19236
Approach
====  
시뮬레이션 + DFS
====  
O(3^16)
====  
====  
- 재귀호출 부분을 구현하는 것은 어렵지 않으나, '매 턴마다 물고기가 주어진 방향으로 움직인다'라는 부분을 구현할 때 복잡하게 구현했으면 디버깅에 다소 긴 시간이 걸릴 수 있는 문제. 처음에는 물고기의 각 위치를 fishes라는 dictionary에 기록해서 물고기가 자리 옮길 때마다 이 dictionary 내 값도 같이 이동했는데, 이 부분에 대해 꼼꼼히 생각하지 못하고 구현하다 보니 디버깅에 정말 많은 시간이 걸렸다. 처음에는 이런 구현이 시간복잡도를 줄이려면 어쩔 수 없는 부분이라고 생각했는데, 문제를 다시 보니 전체 맵의 크기가 그닥 커지지 않기 때문에 고려할 필요 없는 부분이었음. O(n^2)으로 각 물고기의 현재 위치를 찾는 게 제일 간단한 구현. 여기서 시간을 정말 많이 썼는데, **하나의 정보를 여러 변수에 나눠 저장했기 때문에 생길 수밖에 없었던 시간낭비** 같다. 특히 시뮬레이션 문제는 시간복잡도는 크게 고려하지 않아도 되게 문제가 나오는 경우가 많아 구현의 단순함을 좇는 게 더 중요한 것 같다.
=> [PS-137] 백준 19236 청소년상어

solutions/kangwook/programmers 연습문제/아이템줍기.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/87694
Approach
====  
BFS..?
==== 
O(n^2) 
====  
====  
- 굳이 따지자면 bfs 문제긴 한데, bfs 관련 구현보다는 '이 점은 지금 사각형 안인가 밖인가' '이 점은 테두리 위에 있는 점인가 아닌가' 판단을 효율적으로 구현하는 걸 잘하는 게 더 중요한 문제.
- 처음에는 점이 사각형 안에 있는지, 테두리 위에 있는지 여부를 판단하는 걸 어떻게 구현할지 한참 고민하다가 2차원 grid 배열을 만들고 그 안에 1을 채우는 식으로 접근해 풀긴 했는데, 다른 사람들이 푼 걸 보니 그냥 부등식으로 확인하는 부분만 깔끔하게 구현하면 전혀 어렵게 생각할 게 없는 문제였음... 괜히 혼자 조급해서 크게 못 보고 너무 어렵게 생각하는 습관이 잘 안 고쳐지는 거 같다. 좀 더 여유있게 생각할 수 있으면 좋겠는데..
=> [PS-127] 프로그래머스 아이템 줍기

solutions/kangwook/코드트리/나무박멸.py
Link
====
https://www.codetree.ai/training-field/frequent-problems/problems/tree-kill-all/description?page=1&pageSize=20
Approach
====  
시뮬레이션
====  
O(n^2 * k * m)
====  
====  
1. 가독성 측면에서 많은 고민을 했다. 특히 중복 코드가 생기지 않도록 많은 고민을 했다. 되도록이면 한 번의 반복문에서 모든 처리를 하도록 하고, 만약 그것이 불가능하다면 그 한 번의 반복문에서 가능한 모든 후보군을 뽑고 그 다음으로 그 후보군만을 대상으로 하는 반복문을 돌려서 처리를 하는 식으로 코드를 구현했다. 이렇게 하는 것이 구현이 더 간단하다는 생각도 들었고, 보다 결정적으로는, 그렇게 해야 디버깅할 때 여러 개의 비슷한 코드들이 디버깅 과정에서 조금씩 틀려져서 나중에 어디서 틀렸는지 찾기 힘들 정도 상황이 만들어지는 걸 피할 수 있기 때문.
- 베어 있으면서도 '비슷한 코드를 반복해서 쓰지 말고 되도록 한번에 처리하도록 해야 한다'라는 리뷰를 받았는데, 이 코드에서 비로소 그 기억을 되살리게 된 거 같다. 민우님 코드에서 min max함수를 매 loop마다 적용하지 않고 일단 후보군들을 list에 넣은 다음에 sort하는 코드를 봤었는데 그 아이디어가 이 코드 구현의 많은 부분에서 hint가 됐다.
2. 변수, 함수 네이밍 측면에서도 많은 고민을 했다. 기존에는 …
=> [PS-136] 나무 박멸

solutions/kangwook/programmers 연습문제/카운트다운.py
Link
====
https://school.programmers.co.kr/learn/courses/30/lessons/131129
Approach
====  
DP(memoization)
====  
O(n^2)
====  
====  
- 간단한 memoization 문제. 특별히 어려운 조건식이 필요한 문제는 아닌 것 같고, 'memoization으로 접근해볼 수 있겠다'라는 생각만 할 수 있어도 자연스레 코드가 써지는 부류의 문제 같다.
- 다른 사람들 코드들을 보니까 순차적으로 좀 복잡하게 구현한 코드들이 많은데, 굳이 그래야 하는 필요성이 있는지 의문. memoization으로 풀어도 빠르게 풀리고, 구현은 이쪽이 더 쉬움. 주어지는 시간이 짧은 PS에서는 가능한 최대한 간결하고 고민이 덜 필요한 구현을 선택하는 연습을 평소에 할 필요가 있다고 생각. 근데 내가 놓친 게 있을지도 모르니 좀 더 생각해보기는 해야겠다.
=> [PS-125] 프로그래머스 카운트다운
